//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DMS_WindowsService.FTSUpdate {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DMSUpdateDocumentSoap11Binding", Namespace="http://magma.newgen.com")]
    public partial class DMSUpdateDocument : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback updateDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateDataclassOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateDocumentAndDataclassOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DMSUpdateDocument() {
            this.Url = global::DMS_WindowsService.Properties.Settings.Default.DMS_WindowsService_FTSUpdate_DMSUpdateDocument;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event updateDocumentCompletedEventHandler updateDocumentCompleted;
        
        /// <remarks/>
        public event updateDataclassCompletedEventHandler updateDataclassCompleted;
        
        /// <remarks/>
        public event updateDocumentAndDataclassCompletedEventHandler updateDocumentAndDataclassCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:updateDocument", RequestNamespace="http://magma.newgen.com", ResponseNamespace="http://magma.newgen.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string updateDocument([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Inputxml, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string User_Name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("updateDocument", new object[] {
                        Inputxml,
                        User_Name,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateDocumentAsync(string Inputxml, string User_Name, string Password) {
            this.updateDocumentAsync(Inputxml, User_Name, Password, null);
        }
        
        /// <remarks/>
        public void updateDocumentAsync(string Inputxml, string User_Name, string Password, object userState) {
            if ((this.updateDocumentOperationCompleted == null)) {
                this.updateDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateDocumentOperationCompleted);
            }
            this.InvokeAsync("updateDocument", new object[] {
                        Inputxml,
                        User_Name,
                        Password}, this.updateDocumentOperationCompleted, userState);
        }
        
        private void OnupdateDocumentOperationCompleted(object arg) {
            if ((this.updateDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateDocumentCompleted(this, new updateDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:updateDataclass", RequestNamespace="http://magma.newgen.com", ResponseNamespace="http://magma.newgen.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string updateDataclass([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Inputxml, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string User_Name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("updateDataclass", new object[] {
                        Inputxml,
                        User_Name,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateDataclassAsync(string Inputxml, string User_Name, string Password) {
            this.updateDataclassAsync(Inputxml, User_Name, Password, null);
        }
        
        /// <remarks/>
        public void updateDataclassAsync(string Inputxml, string User_Name, string Password, object userState) {
            if ((this.updateDataclassOperationCompleted == null)) {
                this.updateDataclassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateDataclassOperationCompleted);
            }
            this.InvokeAsync("updateDataclass", new object[] {
                        Inputxml,
                        User_Name,
                        Password}, this.updateDataclassOperationCompleted, userState);
        }
        
        private void OnupdateDataclassOperationCompleted(object arg) {
            if ((this.updateDataclassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateDataclassCompleted(this, new updateDataclassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:updateDocumentAndDataclass", RequestNamespace="http://magma.newgen.com", ResponseNamespace="http://magma.newgen.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string updateDocumentAndDataclass([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Inputxml, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string User_Name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DataClassName) {
            object[] results = this.Invoke("updateDocumentAndDataclass", new object[] {
                        Inputxml,
                        User_Name,
                        Password,
                        DataClassName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateDocumentAndDataclassAsync(string Inputxml, string User_Name, string Password, string DataClassName) {
            this.updateDocumentAndDataclassAsync(Inputxml, User_Name, Password, DataClassName, null);
        }
        
        /// <remarks/>
        public void updateDocumentAndDataclassAsync(string Inputxml, string User_Name, string Password, string DataClassName, object userState) {
            if ((this.updateDocumentAndDataclassOperationCompleted == null)) {
                this.updateDocumentAndDataclassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateDocumentAndDataclassOperationCompleted);
            }
            this.InvokeAsync("updateDocumentAndDataclass", new object[] {
                        Inputxml,
                        User_Name,
                        Password,
                        DataClassName}, this.updateDocumentAndDataclassOperationCompleted, userState);
        }
        
        private void OnupdateDocumentAndDataclassOperationCompleted(object arg) {
            if ((this.updateDocumentAndDataclassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateDocumentAndDataclassCompleted(this, new updateDocumentAndDataclassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void updateDocumentCompletedEventHandler(object sender, updateDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void updateDataclassCompletedEventHandler(object sender, updateDataclassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateDataclassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateDataclassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void updateDocumentAndDataclassCompletedEventHandler(object sender, updateDocumentAndDataclassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateDocumentAndDataclassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateDocumentAndDataclassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591